config/routes.rb
Rails.application.routes.draw do
  get '/' => 'patient_summaries#show', as: :patient_summaries_show

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admission.rb
# frozen_string_literal: true

class Admission < ApplicationRecord
  has_many :diagnoses, class_name: 'AdmissionDiagnosis'
  has_many :symptoms
  has_many :observations

  belongs_to :patient
end

app/models/admission_diagnosis.rb
# frozen_string_literal: true

class AdmissionDiagnosis < Diagnosis
  belongs_to :admission
end

app/models/allergy.rb
# frozen_string_literal: true

class Allergy < ApplicationRecord
  belongs_to :patient
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  default_scope { order('id DESC') }

  def date
    moment.strftime('%B %e, %Y')
  end

  def time
    moment.strftime('%I:%M %p')
  end
end

app/models/chronic_condition.rb
# frozen_string_literal: true

class ChronicCondition < Diagnosis
end

app/models/diagnosis.rb
# frozen_string_literal: true

class Diagnosis < ApplicationRecord
  belongs_to :patient

  def described_code
    "#{description} (#{coding_system}#{code})"
  end
end

app/models/diagnostic_procedure.rb
# frozen_string_literal: true

class DiagnosticProcedure < ApplicationRecord
  belongs_to :patient

  def full_description
    "#{description} on #{date}, at #{time}"
  end
end

app/models/facility.rb
# frozen_string_literal: true

class Facility < ApplicationRecord
  has_many :patients
end

app/models/medical_diagnosis.rb
# frozen_string_literal: true

class MedicalDiagnosis < Diagnosis
end

app/models/medication_order.rb
# frozen_string_literal: true

class MedicationOrder < ApplicationRecord
  include ActionView::Helpers::NumberHelper

  enum unit: %i[mg]
  enum route: %i[PO IM SC]

  has_one :frequency, class_name: 'OrderFrequency'
  belongs_to :patient

  def full_medication
    "#{name} #{custom_dosage}#{unit} #{route} #{frequency&.period} to #{necessity}"
  end

  def custom_dosage
    number_with_precision(dosage, precision: 2, strip_insignificant_zeros: true)
  end
end

app/models/observation.rb
# frozen_string_literal: true

class Observation < ApplicationRecord
  belongs_to :admission
end

app/models/order_frequency.rb
# frozen_string_literal: true

class OrderFrequency < ApplicationRecord
  enum unit: %i[hr]
  belongs_to :medication_order

  def period
    "q#{value}#{unit}"
  end
end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  has_many :allergies
  has_many :chronic_conditions
  has_many :medications, class_name: 'MedicationOrder'
  has_many :diagnostic_procedures
  has_many :diagnoses, class_name: 'MedicalDiagnosis'
  has_many :treatments

  belongs_to :facility

  has_one :admission, dependent: :destroy

  enum gender: %i[male female other]

  def age
    ((Time.zone.now - dob.in_time_zone) / 1.year.seconds).floor
  end
end

app/models/symptom.rb
# frozen_string_literal: true

class Symptom < ApplicationRecord
  belongs_to :admission
end

app/models/treatment.rb
# frozen_string_literal: true

class Treatment < ApplicationRecord
  belongs_to :patient

  def full_description
    "#{description} to #{necessity}"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patient_summaries_controller.rb
# frozen_string_literal: true

class PatientSummariesController < ApplicationController
  def show
    @patient = Patient.first
    @facility = Facility.first
    respond_to do |format|
      format.html
      format.pdf do
        pdf = SummaryPdf.new(@patient)
        send_data pdf.render, filename: 'patient_summary', type: 'application/pdf'
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/patient_summaries_helper.rb
# frozen_string_literal: true

module PatientSummariesHelper
  def sentence(array, method)
    array.map(&method).to_sentence(last_word_connector: ' and ')
  end

  def paragraph_1(patient)
    I18n.t('p1', patient_age: patient.age, patient_gender: patient.gender, facility_name: patient.facility.name, patient_admission_date: patient.admission.date, patient_admission_time: patient.admission.time, patient_admission_diagnoses: sentence(patient.admission.diagnoses, :described_code), patient_admission_symptoms: sentence(patient.admission.symptoms, :description), patient_admission_observations: sentence(patient.admission.observations, :description))
  end

  def paragraph_2(patient)
    I18n.t('p2', patient_allegies: sentence(patient.allergies, :description), patient_chronic_conditions: sentence(patient.chronic_conditions, :described_code), patient_medications: sentence(patient.medications, :full_medication))
  end

  def paragraph_3(patient)
    I18n.t('p3', patient_diagnostic_procedures: sentence(patient.diagnostic_procedures, :full_description), patient_diagnoses: sentence(patient.diagnoses, :described_code), patient_treatments: sentence(patient.treatments, :full_description))
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmergencyTransferSummary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patient_summaries/show.html.erb
<div>
  <table class="table table-bordered">
      <thead>
          <tr>
              <th class="active" colspan="4"><%= t('emergency_transfer_summary')%></th>
          </tr>
          <tr>
            <th colspan="4"><%= t('transfering_facility')%></th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td>
                <p> <%= t('name') %> </p>
                <p class="patient-data"><%= @facility.name %></p>
              </td>
              <td colspan="3"></td>
          </tr>
      </tbody>
      <thead>
        <tr>
          <th colspan="4"><%= t('patient_information')%></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="1">
            <p><%= t('first_name')%></p>
            <p class="patient-data"><%= @patient.first_name%></p>
          </td>
          <td>
            <p><%= t('middle_name')%></p>
            <p class="patient-data"><%= @patient.middle_name%></p>
          </td>
          <td>
            <p><%= t('last_name')%></p>
            <p class="patient-data"><%= @patient.last_name %></p>
          </td>
          <td>
            <p><%= t('mr')%></p>
            <p class="patient-data"><%= @patient.mr%></p>
          </td>
        </tr>
      </tbody>
      <tbody>
        <tr>
          <td colspan="4">
            <h5><strong><%= t('summary')%></strong></h5>
            <p class="patient-data">
              <%= paragraph_1(@patient) %>
            </p>
              <p class="patient-data">
                <%= paragraph_2(@patient) %>
            </p>
            <p class="patient-data">
              <%= paragraph_3(@patient) %>
            </p>
          </td>
        </tr>
      </tbody>
  </table>
</div>

<p>
  <%= link_to "Print Summary (PDF)", patient_summaries_show_path(@patient, format: 'pdf') %>
</p>